### ISSUE TITLE
Invalid FileSystemAccess Name: "SeedDB"

### ISSUE THREAD

**Issue by badda71** [Steveice10/BuildTemplate#4]
When using the template to build my 3DS project, I get an error making the CIA with makerom:
```
[EXHEADER ERROR] Invalid FileSystemAccess Name: "SeedDB"
[EXHEADER ERROR] Failed to create ExHeader
[NCCH ERROR] NCCH Build Process Failed
[RESULT] Failed to build outfile
```

Using devkitARM on Windows. makerom version is v0.15, latest release from https://github.com/profi200/Project_CTR/releases

**Comment by Steveice10** [comment]
The latest release on that page is too old. In the first place, building is supposed to be using the makerom binary included with buildtools.

**Comment by badda71** [comment]
ok, thanks - now what version of makerom am I supposed to use?

**Comment by Steveice10** [comment]
Given that there don't seem to be any recent releases there, use a build of the latest source.
